export const PLAYER = {
  MAX_HEALTH: 100,
  MOVEMENT_SPEED_UNITS_PER_SECOND: 7,
  SPAWN: { X: 0, Z: 9 },
  EYE_HEIGHT_UNITS: 1.6,
  INVULNERABILITY_SECONDS: 0.5,
  HEALING_PER_KILL: 1,
  HEALING_PER_WAVE: 15,
  COLLISION_RADIUS_UNITS: 0.4,
  WALL_MARGIN_UNITS: 0.45,
} as const;

export const STAFF = {
  DAMAGE: 1,
  FIRE_INTERVAL_SECONDS: 0.13,
  PROJECTILE_SPEED_UNITS_PER_SECOND: 30,
  PROJECTILE_LIFETIME_SECONDS: 2,
  AIM_RANGE_UNITS: 40,
  MINIMUM_AIM_DISTANCE_UNITS: 1.5,
  MUZZLE_OFFSET_UNITS: { RIGHT: 0.88, DOWN: 0.14, FORWARD: 1.04 },
  PROJECTILE_WALL_INSET_UNITS: 0.01,
  PROJECTILE_CLEANUP_DISTANCE_UNITS: 55,
} as const;

// Each enemy owns its stats. Changing one species must not rebalance another.
export const SLIME = {
  HEALTH: 2,
  DAMAGE: 10,
  BASE_SPEED_UNITS_PER_SECOND: 1.04625,
  SPEED_PER_WAVE_UNITS_PER_SECOND: 0.062,
  SPAWN_DURATION_SECONDS: 2.5,
  ATTACK_REACH_UNITS: 1.25,
  ATTACK_WINDUP_SECONDS: 0.4,
  ATTACK_COOLDOWN_SECONDS: 0.9,
  PUNCH_RECOVERY_SECONDS: 0,
  STOPPING_DISTANCE_UNITS: 0.8125,
  KILL_SCORE: 100,
  COLLISION_RADIUS_UNITS: 0.85,
  HITBOX_RADII_UNITS: { X: 1.05, Y: 0.8, Z: 0.95 },
} as const;

export const ORC = {
  HEALTH: 4,
  DAMAGE: 18,
  BASE_SPEED_UNITS_PER_SECOND: 0.837,
  SPEED_PER_WAVE_UNITS_PER_SECOND: 0.0496,
  SPAWN_DURATION_SECONDS: 0,
  ATTACK_REACH_UNITS: 1.65,
  ATTACK_WINDUP_SECONDS: 0.55,
  ATTACK_COOLDOWN_SECONDS: 1.25,
  PUNCH_RECOVERY_SECONDS: 0.45,
  STOPPING_DISTANCE_UNITS: 1.45,
  KILL_SCORE: 250,
  COLLISION_RADIUS_UNITS: 0.65,
  HITBOX_RADII_UNITS: { X: 0.75, Y: 1.35, Z: 0.6 },
  PLAYER_SEPARATION_UNITS: 1.35,
} as const;

export const WAVES = {
  TOTAL: 5,
  FIRST_WAVE: { SLIMES: 1, ORCS: 1 },
  LATER_WAVE_ENEMY_COUNT: { BASE: 7, PER_WAVE: 5 },
  LATER_WAVE_ORC_PROBABILITY: 0.4,
  INITIAL_READY_WAIT_SECONDS: 2,
  FIRST_WAVE_WAIT_SECONDS: 1.5,
  CLEAR_WAIT_SECONDS: 3,
  SPAWN_INTERVAL_SECONDS: { BASE: 1.1, REDUCTION_PER_WAVE: 0.1, MINIMUM: 0.4 },
  SPAWN_EDGE_INSET_UNITS: 0.8,
  SPAWN_ALONG_INSET_UNITS: 1.5,
  SPAWN_OBSTACLE_CLEARANCE_UNITS: 0.05,
  SPAWN_RELOCATION_ATTEMPTS: 24,
  SPAWN_RELOCATION_STEP_UNITS: 1.5,
} as const;

export const COMBAT = {
  MELEE_IMPACT_TOLERANCE_UNITS: 0.2,
  OBSTACLE_STEERING_DISTANCE_UNITS: 3.2,
  OBSTACLE_STEERING_STRENGTH: 1.8,
  CROWD_SEPARATION_DISTANCE_UNITS: 1.3,
  CROWD_SEPARATION_SHARE: 0.5,
  CROWD_SEPARATION_SPEED_UNITS_PER_SECOND: 1.5,
  ENEMY_WALL_MARGIN_UNITS: 0.6,
} as const;

export const HIT_FEEDBACK = {
  ENEMY_FLASH_SECONDS: 0.14,
  HIT_INDICATOR_SECONDS: 0.1,
  HURT_INDICATOR_SECONDS: 0.35,
} as const;

// Birth growth is shared by rendering and collision volumes.
export const SLIME_BIRTH = {
  SPREAD_END_PROGRESS: 0.3,
  MINIMUM_SCALE: 0.001,
  INITIAL_HEIGHT_SCALE: 0.06,
  INITIAL_WIDTH_SCALE: 1.18,
} as const;
