export const PHOTO_MODE = {
  FIELD_OF_VIEW: { MIN: 35, MAX: 110, DEFAULT: 75, STEP: 1 },
  HEIGHT_UNITS: { MIN: 0.4, MAX: 8, STEP: 0.1 },
  MOVEMENT_SPEED_UNITS_PER_SECOND: 5,
  FAST_MOVEMENT_MULTIPLIER: 3,
  ARENA_MARGIN_UNITS: 12,
  PITCH_LIMIT_RADIANS: 1.55,
  CAPTURE_MAX_WIDTH_PIXELS: 1920,
  CAPTURE_MAX_HEIGHT_PIXELS: 1080,
  MESSAGE_DURATION_MILLISECONDS: 3000,
  DOWNLOAD_URL_LIFETIME_MILLISECONDS: 10_000,
} as const;
